name: tt1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  file_picker: '>=8.1.2'
  intl: 0.20.2
  barcode_widget: ^2.0.0
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.0.0
  webview_flutter: ^4.0.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.0.0
  local_auth: ^2.0.0
  crypto: ^3.0.0
  uuid: ^4.0.0
  flutter_svg: ^2.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  sentry_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.0
  json_serializable: ^6.0.0

dependency_overrides:
  package_info_plus: 8.1.1

flutter:
  uses-material-design: true
  assets:
    - AssetManifest.json
    - assets/images/
    - assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/ic3.png
  remove_alpha_ios: true
